#!/bin/sh
#
# FIXME: I should probably be a perl or python script
#

# FIXME: argument parsing

basedir=$1
builddir=$2
testgroup=$3
testname=$(echo "$4"|sed -e 's/.pl$//')
shift 4

testdir="$basedir/testrun/$testgroup/$testname"
echo "# executing test in $testdir group $testgroup test $testname, builddir $builddir"
rm -rf "$testdir/"
mkdir -p "$testdir"

export TESTOUTDIR="$testdir"
export TESTDIR="$builddir"

exec "$@"
